### ISSUE TITLE
Check if still necessary

### ISSUE THREAD

**Issue by karol-f** [orlin/babel-preset-es2015-mod#1]
I've installed `babel-plugin-transform-es2015-object-super` and added it to `.babelrc`:

```
{
  "plugins": [
      "transform-es2015-object-super"
  ]
}
```

It enabled calling super() in extended classes for IE10. If it will work for you too, maybe we can mention about it in readme.

**Comment by orlin** [comment]
@karol-f I'm not publishing this for universal use, just some of my own node.js workflow (backend) needs.  I just merged a nice pull request so I don't have to explicitly depend on all the es2015 transformation plugins.  I haven't looked at what `object-super` does...  Can it override the following:

``` json
  "transform-es2015-modules-commonjs": { "loose": true },
  "transform-regenerator": { "async": false, "asyncGenerators": false }
```

Or maybe you are saying I may not need this module at all and just use `.babelrc`?  What would you say in the readme?
